#!/bin/bash

#Detect Brute Force Attempts
#Dirty run-through

while true; do
   #Grab all failed entries since last log clear
   cat /var/log/maillog | grep "failed" > /var/log/failed.txt

   #Let's just grab the usernames of failed logins. 
   #Putting just the names in tmp.txt
   cat /var/log/failed.txt | awk '{print $11}' > /var/log/tmp.txt

   if [ -s "/var/log/tmp.txt" ]
   then
	printf "\nNumber of failed attempts per user:\n\n"
   else
	echo -n "" > /var/log/maillog
   fi

   #Find unique mentions of users who failed to login
   for line in `cat /var/log/tmp.txt | sort | uniq`; do
	#Store in variable $tmp the amount of failed logins per each unique username
	tmp=`grep -o $line /var/log/failed.txt | wc -l | tr -s " "`
	#If number per unique mention is 5 or above, print that unique username
	#and their corresponding number of failed login attempts
	if [ "$tmp" -gt 4 ]; then
		echo "$line: "
		echo $tmp
	else
		break
	fi
	printf "\n"
   done

   #Preserve this data in file2.txt 
   cat /var/log/maillog >> /var/log/maillog2

   #Clear out log we are using for this script
   echo -n "" > /var/log/maillog

   #Clear failed.txt for next run
   echo -n "" > /var/log/failed.txt

   #Remove tmp.txt
   rm -f /var/log/tmp.txt

   sleep 3m;

done
